In [4]:
import pandas as pd

In [6]:
cd C:\Users\Chengda\Desktop

C:\Users\Chengda\Desktop

In [16]:
df=pd.read_csv('GDP.csv')

In [17]:
df.head()

,Unnamed: 0,Country,GDP,GDP (abbrev),GDP growth,Population,GDP per capita,Share of World GDP
0,1,United States,"$19,485,394,000,000",$19.485 trillion,2.27%,"325,084,756","$59,939",24.08%
1,2,China,"$12,237,700,479,375",$12.238 trillion,6.90%,"1,421,021,791","$8,612",15.12%
2,3,Japan,"$4,872,415,104,315",$4.872 trillion,1.71%,"127,502,725","$38,214",6.02%
3,4,Germany,"$3,693,204,332,230",$3.693 trillion,2.22%,"82,658,409","$44,680",4.56%
4,5,India,"$2,650,725,335,364",$2.651 trillion,6.68%,"1,338,676,785","$1,980",3.28%

In [25]:
df.drop(['Unnamed: 0'],axis=1)

,Country,GDP,GDP (abbrev),GDP growth,Population,GDP per capita,Share of World GDP
0,United States,"$19,485,394,000,000",$19.485 trillion,2.27%,"325,084,756","$59,939",24.08%
1,China,"$12,237,700,479,375",$12.238 trillion,6.90%,"1,421,021,791","$8,612",15.12%
2,Japan,"$4,872,415,104,315",$4.872 trillion,1.71%,"127,502,725","$38,214",6.02%
3,Germany,"$3,693,204,332,230",$3.693 trillion,2.22%,"82,658,409","$44,680",4.56%
4,India,"$2,650,725,335,364",$2.651 trillion,6.68%,"1,338,676,785","$1,980",3.28%
...,...,...,...,...,...,...,...
184,Sao Tome & Principe,"$392,570,293",$393 million,3.87%,"207,089","$1,896",0.00%
185,Palau,"$289,823,500",$290 million,-3.57%,"17,808","$16,275",0.00%
186,Marshall Islands,"$204,173,430",$204 million,3.60%,"58,058","$3,517",0.00%
187,Kiribati,"$185,572,502",$186 million,0.33%,"114,158","$1,626",0.00%
188,Tuvalu,"$39,731,317",$40 million,3.24%,"11,370","$3,494",0.00%

In [26]:
df.head()

,Unnamed: 0,Country,GDP,GDP (abbrev),GDP growth,Population,GDP per capita,Share of World GDP
0,1,United States,"$19,485,394,000,000",$19.485 trillion,2.27%,"325,084,756","$59,939",24.08%
1,2,China,"$12,237,700,479,375",$12.238 trillion,6.90%,"1,421,021,791","$8,612",15.12%
2,3,Japan,"$4,872,415,104,315",$4.872 trillion,1.71%,"127,502,725","$38,214",6.02%
3,4,Germany,"$3,693,204,332,230",$3.693 trillion,2.22%,"82,658,409","$44,680",4.56%
4,5,India,"$2,650,725,335,364",$2.651 trillion,6.68%,"1,338,676,785","$1,980",3.28%

In [29]:
dfU=pd.read_csv('unemployement.csv')
dfU.head()

                  Country   Last  Previous Reference Unit
0                 Namibia  33.40     34.00    18-Dec    %
1  Bosnia and Herzegovina  32.75     32.61    20-Jan    %
2                  Angola  31.80     30.10    19-Dec    %
3            South Africa  29.10     29.10    19-Dec    %
4                  Kosovo  25.90     24.50    19-Dec    %

In [33]:
dfUhigh=dfU[dfU['Last']>8.5]
dfUhigh

                   Country   Last  Previous Reference Unit
0                  Namibia  33.40     34.00    18-Dec    %
1   Bosnia and Herzegovina  32.75     32.61    20-Jan    %
2                   Angola  31.80     30.10    19-Dec    %
3             South Africa  29.10     29.10    19-Dec    %
4                   Kosovo  25.90     24.50    19-Dec    %
5               Mozambique  25.04     24.37    17-Dec    %
6                Palestine  24.00     24.60    19-Dec    %
7                  Lesotho  23.50     23.60    19-Dec    %
8                  Nigeria  23.10     22.70    18-Sep    %
9                Swaziland  22.90     22.50    19-Dec    %
10                   Gabon  19.60     19.50    19-Dec    %
11                Ethiopia  19.10     16.90    18-Dec    %
12                  Jordan  19.00     19.10    19-Dec    %
13                 Senegal  19.00     15.10    19-Mar    %
14                Botswana  18.20     17.90    19-Dec    %
15                 Armenia  17.90     18.00    19-Dec    %
16                   Libya  17.30     17.30    19-Dec    %
17               Macedonia  16.60     17.10    19-Dec    %
18                  Greece  16.40     16.40    20-Jan    %
19                  Rwanda  15.40     16.00    19-Nov    %
20              Montenegro  15.35     16.21    20-Jan    %
21                 Tunisia  14.90     15.10    19-Dec    %
22                  Guyana  13.80     12.20    18-Dec    %
23                   Spain  13.80     13.92    19-Dec    %
24                  Turkey  13.80     13.70    20-Jan    %
25                   Haiti  13.50     13.50    19-Dec    %
26   Sao Tome and Principe  13.40     13.30    19-Dec    %
27                  Zambia  13.20     11.40    19-Dec    %
28                   Sudan  13.00     12.90    19-Dec    %
29                   Yemen  12.80     12.90    19-Dec    %
30                 Georgia  12.70     13.90    18-Dec    %
31              Costa Rica  12.40     11.40    19-Dec    %
32                 Austria  12.20      8.10    20-Mar    %
33              Cape Verde  12.20     12.20    18-Dec    %
34                Colombia  12.20     13.00    20-Feb    %
35           New Caledonia  11.90     11.60    18-Dec    %
36                 Albania  11.60     11.80    19-Dec    %
37                  Brazil  11.60     11.20    20-Feb    %
38                 Algeria  11.40     11.70    19-Apr    %
39             Afghanistan  11.10     11.10    19-Dec    %
40                 Uruguay  10.50      8.50    20-Feb    %
41                    Iran  10.40     10.90    19-Sep    %
42   Republic of the Congo  10.40     10.40    19-Dec    %
43              Mauritania  10.32     10.31    19-Dec    %
44               Lithuania   9.80      9.40    20-Mar    %
45                    Mali   9.80      9.60    19-Dec    %
46                   Italy   9.70      9.80    20-Feb    %
47                  Serbia   9.70      9.50    19-Dec    %
48                Tanzania   9.70      9.90    18-Dec    %
49                 Bahamas   9.50     10.70    19-Dec    %
50                  Belize   9.40      9.00    18-Dec    %
51       Equatorial Guinea   9.20      9.20    19-Dec    %
52                 Morocco   9.20      9.40    19-Dec    %
53                  Brunei   9.10      8.90    19-Dec    %
54             Puerto Rico   9.10      8.50    19-Dec    %
55               Argentina   8.90      9.70    19-Dec    %
56                Barbados   8.90      9.50    19-Dec    %
57                  Gambia   8.90      8.90    19-Dec    %
58                 Ukraine   8.70      7.30    19-Dec    %

In [34]:
from bokeh.plotting import figure, output_file, show,output_notebook
output_notebook()

In [35]:
def make_dashboard(x, gdp_change, unemployment, title, file_name):
    output_file(file_name)
    p = figure(title=title, x_axis_label='year', y_axis_label='%')
    p.line(x.squeeze(), gdp_change.squeeze(), color="firebrick", line_width=4, legend="% GDP change")
    p.line(x.squeeze(), unemployment.squeeze(), line_width=4, legend="% unemployed")
    show(p)

In [36]:
combined=pd.merge(df, dfU, how='left', on='Country')

In [38]:
combined.drop(['Unnamed: 0'],axis=1)

,Country,GDP,GDP (abbrev),GDP growth,Population,GDP per capita,Share of World GDP,Last,Previous,Reference,Unit
0,United States,"$19,485,394,000,000",$19.485 trillion,2.27%,"325,084,756","$59,939",24.08%,4.4,3.5,20-Mar,%
1,China,"$12,237,700,479,375",$12.238 trillion,6.90%,"1,421,021,791","$8,612",15.12%,5.9,6.2,20-Mar,%
2,Japan,"$4,872,415,104,315",$4.872 trillion,1.71%,"127,502,725","$38,214",6.02%,2.4,2.4,20-Feb,%
3,Germany,"$3,693,204,332,230",$3.693 trillion,2.22%,"82,658,409","$44,680",4.56%,3.2,3.2,20-Feb,%
4,India,"$2,650,725,335,364",$2.651 trillion,6.68%,"1,338,676,785","$1,980",3.28%,7.8,7.2,20-Feb,%
...,...,...,...,...,...,...,...,...,...,...,...
184,Sao Tome & Principe,"$392,570,293",$393 million,3.87%,"207,089","$1,896",0.00%,NaN,NaN,NaN,NaN
185,Palau,"$289,823,500",$290 million,-3.57%,"17,808","$16,275",0.00%,NaN,NaN,NaN,NaN
186,Marshall Islands,"$204,173,430",$204 million,3.60%,"58,058","$3,517",0.00%,NaN,NaN,NaN,NaN
187,Kiribati,"$185,572,502",$186 million,0.33%,"114,158","$1,626",0.00%,NaN,NaN,NaN,NaN
188,Tuvalu,"$39,731,317",$40 million,3.24%,"11,370","$3,494",0.00%,NaN,NaN,NaN,NaN

In [42]:
filename2='https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/projects/coursera_project/clean_gdp.csv'

In [43]:
x=pd.read_csv(filename2)

x.head()

   date  level-current  level-chained  change-current  change-chained
0  1948          274.8         2020.0            -0.7            -0.6
1  1949          272.8         2008.9            10.0             8.7
2  1950          300.2         2184.0            15.7             8.0
3  1951          347.3         2360.0             5.9             4.1
4  1952          367.7         2456.1             6.0             4.7

In [44]:
x[x['date']

SyntaxError: unexpected EOF while parsing (<ipython-input-44-b0a004aa42c6>, line 1)

In [46]:
filename2='https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/projects/coursera_project/clean_gdp.csv'

In [47]:
gdp_change=pd.read_csv(filename2)

gdp_change.head()

   date  level-current  level-chained  change-current  change-chained
0  1948          274.8         2020.0            -0.7            -0.6
1  1949          272.8         2008.9            10.0             8.7
2  1950          300.2         2184.0            15.7             8.0
3  1951          347.3         2360.0             5.9             4.1
4  1952          367.7         2456.1             6.0             4.7

In [60]:
gdp_change['change-current']

0     -0.7
1     10.0
2     15.7
3      5.9
4      6.0
      ...
64     3.6
65     4.4
66     4.0
67     2.7
68     4.2
Name: change-current, Length: 69, dtype: float64

In [48]:
filename3='https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/projects/coursera_project/clean_unemployment.csv'

In [49]:
unemployment=pd.read_csv(filename3)

unemployment.head()

   date  unemployment
0  1948      3.750000
1  1949      6.050000
2  1950      5.208333
3  1951      3.283333
4  1952      3.025000

In [59]:
unemployment['unemployment']

0     3.750000
1     6.050000
2     5.208333
3     3.283333
4     3.025000
        ...
64    8.075000
65    7.358333
66    6.158333
67    5.275000
68    4.875000
Name: unemployment, Length: 69, dtype: float64

In [61]:
make_dashboard(x['date'],gdp_change['change-current'],unemployment['unemployment'],'GDP growth - unemployment', 'GDP - unemployment')

BokehDeprecationWarning: 'legend' keyword is deprecated, use explicit 'legend_label', 'legend_field', or 'legend_group' keywords instead
BokehDeprecationWarning: 'legend' keyword is deprecated, use explicit 'legend_label', 'legend_field', or 'legend_group' keywords instead